language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.4

# Command to install dependancies
install: pip install -r requirements.txt

# Command to run tests
script: python run_tests.py
#
# A more common way to initiate tests would be one of the 
# following.  We'll discuss and migrate to these mechanisms
# at some point in the future.
#script: nosetests
#script: python setup.py test
